to_do/urls.py
from django.urls import path
from . import views


app_name = "to_do"
urlpatterns = [
    path('', views.ToDoList.as_view(), name="index"),
    path("delete/<int:pk>", views.ToDoDelete.as_view(), name="delete"),
    path("create", views.ToDoCreate.as_view(), name="create"),
    path("create/<int:pk>", views.ToDoUpdate.as_view(), name="update"),
]

to_do_improved/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('to_do.urls')),
]

to_do/models.py
from django.db import models

# Create your models here.
class ToDo(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=240)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.content

to_do/views.py
from django.shortcuts import render
from .models import ToDo
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.views.generic import DeleteView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

# Create your views here.
class ToDoList(ListView):
    model = ToDo
    template_name = "to_do/index.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["all_to_dos"] = ToDo.objects.all().order_by("-date_created").order_by("-completed")
        return context


class ToDoDelete(DeleteView):
    model = ToDo
    success_url = reverse_lazy('to_do:index')

class ToDoCreate(CreateView):
    model = ToDo
    success_url = reverse_lazy('to_do:index')
    fields = ["content"]

class ToDoUpdate(UpdateView):
    model = ToDo
    success_url = reverse_lazy('to_do:index')
    fields = ["content", "completed"]

to_do/templates/to_do/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>To-Do</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

to_do/templates/to_do/index.html
{% extends "to_do/base.html" %}

{% block content %}
  <div class="container">
    <h1>To Do App</h1>
    <table border="solid" class="table table-striped">
      <thead>
        <th>Task</th>
        <th>Date</th>
        <th>Completed</th>
        <th>Delete</th>
        <th>Update</th>
      </thead>

      {% for todo in all_to_dos %}
      <tr>
        <td>{{ todo.content }}</td>
        <td>{{ todo.date_created }}</td>
        <td>{{ todo.completed }}</td>
        <td><a href="{% url "to_do:delete" todo.pk %}">Delete</a></td>
        <td><a href="{% url "to_do:update" todo.pk %}">Update</a></td>
      </tr>
      {% endfor %}
    </table>

    <a href="{% url "to_do:create" %}">Create New Task</a>
  </div>
{% endblock %}

to_do/templates/to_do/todo_confirm_delete.html
{% extends "to_do/base.html" %}

{% block content %}
<div class="container">
  <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ object }}"?</p>
      <input type="submit" value="Confirm">
  </form>
</div>
{% endblock content %}

to_do/templates/to_do/todo_form.html
{% extends "to_do/base.html" %}

{% block content %}
<div class="container">
  <form method="post">{% csrf_token %}
      <h2>Create Task</h2>
      {{ form.as_p }}
      <input type="submit" value="Confirm">
  </form>
</div>
{% endblock content %}